### ISSUE TITLE
Start the project

### ISSUE THREAD

**Issue by burakuluu** [expalmer/react-progress-form#2]
How can I start the project on my localhost? I run gulp command and it created the index.html under the dist folder but what is next?

**Comment by expalmer** [comment]
Sorry! I have to update this repo. I'm going to put the instructions.
Thanks.

**Comment by burakuluu** [comment]
I'll close the issue when you give an update here. Thank you :)

**Comment by expalmer** [comment]
Done! Take a look on readme again...you have to run `npm run build` to generate the `dist` folder.

**Comment by burakuluu** [comment]
You edited wrong. It has to be '**npm run build**' instead of '**npm run gulp**' because '**build**' is what you declared in your **package.json** 

Also even if we write **npm run build**, it will again just run the gulp function and it doesn't allocate any socket to listen. I mean, _how can we run the demo version in our localhost such as http://localhost:8080?_ This edit that you did doesn't run the project on our localhost.  Here's the screenshot I took when I write npm run build;

![gulp](https://cloud.githubusercontent.com/assets/25999821/25483446/8989f80e-2b5e-11e7-8595-a7d90c3a1d38.JPG)

**Comment by expalmer** [comment]
OMG sorry!

**Comment by expalmer** [comment]
I fixed there.
After the build, you only have to open the `dist/index.html`.

**Comment by burakuluu** [comment]
Thank you. I now can run it :)
